### ISSUE TITLE
LB has problem with data for hourly plot

### ISSUE THREAD

**Issue by nortikin** [ladybug-tools/ladybug-blender#2]
json:
https://gist.github.com/5aabbfab1a8eff31dd234c46efa33c23

![изображение](https://user-images.githubusercontent.com/5783432/94480922-a4d9bd00-01df-11eb-8f05-e69f8832dda3.png)
![изображение](https://user-images.githubusercontent.com/5783432/94481026-cdfa4d80-01df-11eb-8bb8-85ced9888186.png)

**Comment by nortikin** [comment]
```
File "/home/ololo/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 31, in execute
    node.refresh()
  File "/home/ololo/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 57, in refresh
    self.process()
  File "/home/ololo/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 74, in process
    for geometries in socket.sv_get():
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/core/sockets.py", line 125, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/core/socket_data.py", line 121, in SvGetSocket
    raise SvNoDataError(socket, msg="not found in socket_data_cache")
sverchok.core.socket_data.SvNoDataError: node LB Out.003 (socket geometry) not found in socket_data_cache

```

**Comment by Durman** [comment]
Try to `update` the tree via the button on the N panel.

**Comment by Moult** [comment]
The trace looks like you simply need to update the tree as @Durman  suggested.

I was unable to repoduce - I cannot import the gist, I these these messages... ideas?

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 753, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 745, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "LB PMV Comfort" not found'
2020-09-29 17:55:38,593    ERROR logging.py 165 'bpy_prop_collection[key]: key "LB Out.001" not found'
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 753, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 745, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "LB Out.001" not found'
2020-09-29 17:55:38,593    ERROR logging.py 165 'bpy_prop_collection[key]: key "LB Out.001" not found'
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 753, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 745, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "LB Out.001" not found'
2020-09-29 17:55:38,593    ERROR logging.py 165 'bpy_prop_collection[key]: key "LB Out.001" not found'
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 753, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/dion/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 745, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "LB Out.001" not found'
2020-09-29 17:55:38,594    ERROR logging.py 165 failed total: 91
2020-09-29 17:55:38,594    ERROR logging.py 165 [['LB Out', 0, 'Viewer Draw Mk3', 0], ['LB Out', 1, 'Viewer Draw Mk3', 1], ['LB Out', 2, 'Viewer Draw Mk3', 2], ['A Number.007', 0, 'LB Analysis Period', 0], ['A Number.008', 0, 'LB Analysis Period', 1], ['A Number.010', 0, 'LB Analysis Period', 2], ['A Number.007', 0, 'LB Analysis Period', 3], ['A Number.008', 0, 'LB Analysis Period', 4], ['A Number.011', 0, 'LB Analysis Period', 5], ['A Number.009', 0, 'LB Analysis Period', 6], ['File Path', 0, 'LB Import EPW', 0], ['LB Import EPW', 0, 'LB Indoor Solar MRT', 0], ['LB Import EPW', 1, 'LB Indoor Solar MRT', 1], ['LB Import EPW', 6, 'LB Indoor Solar MRT', 2], ['LB Import EPW', 7, 'LB Indoor Solar MRT', 3], ['A Number.002', 0, 'LB Indoor Solar MRT', 4], ['A Number.003', 0, 'LB Indoor Solar MRT', 5], ['A Number.003', 0, 'LB Indoor Solar MRT', 6], ['A Number.002', 0, 'LB Indoor Solar MRT', 7], ['Logic functions', 0, 'LB Indoor Solar MRT', 9], ['LB Import EPW', 1, 'LB PMV Comfort', 0], ['LB Indoor Solar MRT', 2, 'LB PMV Comfort', 1], ['LB Import EPW', 3, 'LB PMV Comfort', 2], ['LB Import EPW', 4, 'LB PMV Comfort', 3], ['A Number.005', 0, 'LB PMV Comfort', 4], ['A Number.004', 0, 'LB PMV Comfort', 5], ['Logic functions.001', 0, 'LB PMV Comfort', 7], ['LB PMV Comfort', 0, 'LB Hourly Plot.002', 0], ['Vector in.002', 0, 'LB Hourly Plot.002', 1], ['Note', 0, 'LB Hourly Plot.002', 7], ['LB Analysis Period', 0, 'LB Hourly Plot.002', 8], ['LB Hourly Plot.002', 0, 'LB Out.003', 0], ['LB Hourly Plot.002', 1, 'LB Out.003', 1], ['LB Hourly Plot.002', 2, 'LB Out.003', 2], ['LB Hourly Plot.002', 3, 'LB Out.003', 3], ['LB Hourly Plot.002', 4, 'LB Out.003', 4], ['LB Out.003', 0, 'Viewer Draw Mk3.002', 0], ['LB Out.003', 1, 'Viewer Draw Mk3.002', 1], ['LB Out.003', 2, 'Viewer Draw Mk3.002', 2], ['LB Indoor Solar MRT', 1, 'LB Deconstruct Header', 0], ['A Number', 0, 'LB SunPath', 0], ['LB Import EPW', 0, 'LB SunPath', 1], ['LB Analysis Period', 1, 'LB SunPath', 2], ['Vector in', 0, 'LB SunPath', 5], ['A Number.001', 0, 'LB SunPath', 6], ['LB Import EPW', 1, 'LB SunPath', 9], ['LB SunPath', 4, 'LB Out.005', 0], ['LB SunPath', 5, 'LB Out.005', 1], ['LB SunPath', 6, 'LB Out.005', 2], ['LB SunPath', 7, 'LB Out.005', 3], ['LB SunPath', 8, 'LB Out.005', 4], ['LB SunPath', 9, 'LB Out.005', 5], ['LB SunPath', 10, 'LB Out.005', 6], ['LB Indoor Solar MRT', 1, 'LB Hourly Plot.001', 0], ['Vector in.001', 0, 'LB Hourly Plot.001', 1], ['LB Hourly Plot.001', 0, 'LB Out.002', 0], ['LB Hourly Plot.001', 1, 'LB Out.002', 1], ['LB Hourly Plot.001', 2, 'LB Out.002', 2], ['LB Hourly Plot.001', 3, 'LB Out.002', 3], ['LB Hourly Plot.001', 4, 'LB Out.002', 4], ['LB Out.005', 0, 'Viewer Draw Mk3.005', 0], ['LB Out.005', 1, 'Viewer Draw Mk3.005', 1], ['LB Out.005', 2, 'Viewer Draw Mk3.005', 2], ['Objects in.001', 5, 'List Join.001', 0], ['Objects in', 5, 'List Join', 0], ['LB SunPath', 0, 'LB Direct Sun Hours', 0], ['List Join.001', 0, 'LB Direct Sun Hours', 2], ['List Join', 0, 'LB Direct Sun Hours', 3], ['A Number.006', 0, 'LB Direct Sun Hours', 4], ['Logic functions.002', 0, 'LB Direct Sun Hours', 8], ['LB Direct Sun Hours', 2, 'LB Out.004', 0], ['LB Direct Sun Hours', 3, 'LB Out.004', 1], ['LB Direct Sun Hours', 4, 'LB Out.004', 2], ['LB Out.004', 0, 'Viewer Draw Mk3.004', 0], ['LB Out.004', 1, 'Viewer Draw Mk3.004', 1], ['LB Out.004', 2, 'Viewer Draw Mk3.004', 2], ['LB Deconstruct Header', 0, 'Stethoscope MK2', 0], ['LB Import EPW', 1, 'LB Hourly Plot', 0], ['LB Hourly Plot', 0, 'Stethoscope MK2.001', 0], ['LB Hourly Plot', 0, 'LB Out.001', 0], ['LB Hourly Plot', 1, 'LB Out.001', 1], ['LB Hourly Plot', 2, 'LB Out.001', 2], ['LB Hourly Plot', 3, 'LB Out.001', 3], ['LB Hourly Plot', 4, 'LB Out.001', 4], ['LB Out.002', 0, 'Viewer Draw Mk3.001', 0], ['LB Out.002', 1, 'Viewer Draw Mk3.001', 1], ['LB Out.002', 2, 'Viewer Draw Mk3.001', 2], ['LB PMV Comfort', 0, 'Stethoscope MK2.002', 0], ['LB Out.001', 0, 'Viewer Draw Mk3.003', 0], ['LB Out.001', 1, 'Viewer Draw Mk3.003', 1], ['LB Out.001', 2, 'Viewer Draw Mk3.003', 2]]
```

**Comment by Durman** [comment]
The messages says that a link can't be created because node with name `LB Out.001` was not found. Probably the node itself was not imported for some reason. Any way I would not worry about this problem till merging this PR.

https://github.com/nortikin/sverchok/pull/3560

**Comment by nortikin** [comment]
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb149e6d550>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb149e6dbd0>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef1b3550>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb149e6d050>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb149e6dd10>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb149e6d750>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef1638d0>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163950>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163f50>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163ad0>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163a50>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163f10>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163310>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163090>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163a90>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0ef163b50>
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0e97106d0>

**Comment by nortikin** [comment]
ok, i see, i have installed some time ago ladybugs_tools. it seems not the same as this repo.
simbolic link to github clone + deploy with python3 for linux usage

**Comment by nortikin** [comment]
installed twine:
```
Pushing new version to PyPi
usage: twine upload [-h] [-r REPOSITORY] [--repository-url REPOSITORY_URL]
                    [-s] [--sign-with SIGN_WITH] [-i IDENTITY] [-u USERNAME]
                    [-p PASSWORD] [-c COMMENT] [--config-file CONFIG_FILE]
                    [--skip-existing] [--cert path] [--client-cert path]
                    [--verbose] [--disable-progress-bar]
                    dist [dist ...]
twine upload: error: argument -u/--username: expected one argument

```

**Comment by nortikin** [comment]
~/git/ladybug-blender$ ls build/lib/ladybug_tools/nodes/ladybug/
__init__.py  LB_Out.py

**Comment by nortikin** [comment]
ok, i see there is nothing in github repo

**Comment by nortikin** [comment]
```
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3754.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3754.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3755.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3755.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3756.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3756.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3757.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3757.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3758.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3758.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3759.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3759.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3760.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3760.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3761.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3761.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3762.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3762.0
WARNING: geometry <class 'float'> not yet supported in Sverchok: 3763.0
WARNING: geometry <class 'float'> not yet supported in Blender: 3763.0

```

**Comment by Moult** [comment]
@nortikin the `LB Out` node does two things:

 1. Take ladybug input geometry and bake it to the scene as Blender objects
 2. Take ladybug input geometry and convert it to data that can be used by sverchok. At the moment, these are the three outputs of `verts`, `edges`, and `faces`.

Because there are quite a few geometry types in Ladybug, I decided to spit out a warning on anything which I can't yet translate, just in case there is a good way to translate it in the future.

The message `WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7fb0e97106d0>` means that the `LB Out` node does not know how to convert text objects into something that Sverchok can use. One option is to convert it into a list of strings, but that would lose the 3D formatting and location of the text. I'm not sure how useful a list of strings would be to be honest. Maybe I should just suppress that warning and make the decision that LadybugText objects simply are not useful to be converted as an input to other Sverchok nodes.

The message `WARNING: geometry <class 'float'> not yet supported in Sverchok: 3754.0` means that you have plugged in a non-geometry connection into the `LB Out` node. The `LB Out` node only visualises geometry, whereas you've likely plugged in a list of data, so it's complaining that it doesn't know what to do with it :) Again, maybe I should suppress this.

**Comment by nortikin** [comment]
@Moult you better separate `LB viewer` and `LB out` nodes to solve two problems aside.
