### ISSUE TITLE
oduleNotFoundError: No module named 'space_view3d_point_cloud_visualizer' following the demo example

### ISSUE THREAD

**Issue by ebo** [ladybug-tools/ladybug-blender#36]
While following the published demo <https://www.youtube.com/watch?v=rMCuSwsF2aM> I get the following error:

Error: Python: Traceback (most recent call last):
  File "/home/ebo/.config/blender/2.93/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 33, in execute
    node.refresh()
  File "/home/ebo/.config/blender/2.93/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 60, in refresh
    self.process()
  File "/home/ebo/.config/blender/2.93/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 81, in process
    self.create_blender_colored_v()
  File "/home/ebo/.config/blender/2.93/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 322, in create_blender_colored_v
    from space_view3d_point_cloud_visualizer import PCVControl
ModuleNotFoundError: No module named 'space_view3d_point_cloud_visualizer'

I have not been able to find where space_view3d_point_cloud_visualizer and/or PCVControl is defined.

I am currently running blender-2.93 with yesterday's (20220106) release of ladybug, and sverchok-master.  I get roughly through 4:10 of the demo video where it is refreshing after adding the analysis period.

I also get numerous warnings:

WARNING: geometry <class 'ladybug_tools.colorize.ColoredPoint'> not yet supported in Sverchok: <ladybug_tools.colorize.ColoredPoint object at 0x7f7c4930e910>
and 
WARNING: geometry <class 'ladybug_tools.text.LadybugText'> not yet supported in Sverchok: <ladybug_tools.text.LadybugText object at 0x7f7c4cd7a550>

Are their any updates that have not been merged back into the master branch?  Am I running the correct one (as per the ladybug docs)?

Thanks!

**Comment by Moult** [comment]
https://github.com/uhlik/bpy/blob/master/space_view3d_point_cloud_visualizer.py
