### ISSUE TITLE
Fails to enable in Blender Preferences

### ISSUE THREAD

**Issue by ghost** [ladybug-tools/ladybug-blender#41]
I followed the readme instructions for installing Sverchok (1.2.0) and Ladybug Tools (220127) addons on Blender 3.5.1. Both add-ons install successfully and Sverchok can be enabled from the Blender Preferences. However, when I check the enable Ladybug Tools in Blender Preferences, I get the following error:

```
Traceback (most recent call last):
  File "/Applications/Blender 3.51.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/Me/Library/Application Support/Blender/3.5/scripts/addons/ladybug_tools/__init__.py", line 25, in <module>
    from sverchok.core import sv_registration_utils, make_node_list
ImportError: cannot import name 'sv_registration_utils' from 'sverchok.core' (/Users/Me/Library/Application Support/Blender/3.5/scripts/addons/sverchok-master/core/__init__.py)
```

Ladybug Tools fails to enable on both Windows and Mac (Apple Silicon).

**Comment by Durman** [comment]
I guess you have to use Sverchok 1.1 because there were changes in 1.2 which was not reflected in Ladybug tools.

**Comment by tjrhyder** [comment]
Thanks @Durman! Sverchok 1.1 allows me to enable the Ladybug tools.

For others with this problem, the branch can be found here:
https://github.com/nortikin/sverchok/tree/v1.1.0

After installing 1.1 I had to remove the dots and rename the addon in the scripts folder to `sverchok-master`.

**Comment by Durman** [comment]
Also it can be installed from the release page - https://github.com/nortikin/sverchok/releases/tag/v1.1.0
In this case there is no need in the renaming step.

**Comment by Andrej730** [comment]
Can be closed after #44
