### ISSUE TITLE
Error while generating colored points

### ISSUE THREAD

**Issue by Sinasta** [ladybug-tools/ladybug-blender#9]
I always get an error when trying to generate colored points (legend or data).
Im on Manjaro (Arch linux) and Blender 2.90.1
I have sverchok, ladubug tools and point cloud visualizer installed.
![Screenshot from 2020-10-02 10-08-21](https://user-images.githubusercontent.com/64699866/94902106-f613d600-0497-11eb-83c5-34a5456071f4.png)

Error: 2020-10-02 10:08:12,148 [ERROR] sverchok.core.update_system: Node LB SunPath had exception: __init__() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/home/sinasta/.config/blender/2.90/scripts/addons/sverchok-master/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_SunPath.py", line 71, in process
    self.process_ladybug(*sv_input)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_SunPath.py", line 278, in process_ladybug
    col_pt = ColoredPoint(pt)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/colorize.py", line 14, in __init__
    self.color = black()
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/color.py", line 25, in black
    return Color(0, 0, 0, 255)
TypeError: __init__() takes 4 positional arguments but 5 were given

**Comment by Sinasta** [comment]
Different error for hourly plot visualisation:

2020-10-02 10:16:18,320 [ERROR] sverchok.core.update_system: Node LB Out had exception: 'Color' object has no attribute 'a'
Traceback (most recent call last):
  File "/home/sinasta/.config/blender/2.90/scripts/addons/sverchok-master/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 76, in process
    self._process_geometry(geometry)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 88, in _process_geometry
    self._process_geometry(g)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 91, in _process_geometry
    self._process_blender_geometry(geometry)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 121, in _process_blender_geometry
    self.blender_from_mesh(geometry)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 218, in blender_from_mesh
    name = get_material_name(color)
  File "/home/sinasta/.config/blender/2.90/scripts/addons/ladybug_tools/nodes/ladybug/LB_Out.py", line 212, in get_material_name
    return 'ladybug-{}-{}-{}-{}'.format(color.r, color.g, color.b, color.a)
AttributeError: 'Color' object has no attribute 'a'
![Screenshot from 2020-10-02 10-18-07](https://user-images.githubusercontent.com/64699866/94902535-9d910880-0498-11eb-9d9a-8235bcb1bcaf.png)

**Comment by mostaphaRoudsari** [comment]
The error looks like to come from using an older version of ladybug before [this commit](https://github.com/ladybug-tools/ladybug/commit/05f105a7f930e0172159bc20fc44c9f490e8161e) when the opacity is added to RGB color. Can you update the ladybug library on your machine?

You should also be able to run `path/to/python/that/is/used/by/blender -m pip show lbt-ladybug` to see what is the installed version.

**Comment by Sinasta** [comment]
Thank You very much. Updating lbt-ladybug solved the problem

**Comment by mostaphaRoudsari** [comment]
@Sinasta, great to know! Do you know why this happened? Did you install ladybug prior to using the ladybug plugin for Blender?

@Moult, don't you package the libraries with the distribution? Or are we using the global python installation so people can end up with a different version?

**Comment by Moult** [comment]
@Sinasta this does indeed sound odd and should not have happened. The libraries are packaged with the add-on as @mostaphaRoudsari  says so you should not have to manually pip install anything, and I believe it should be the latest entry in `sys.path`. Can you elaborate on how you installed the add-on, and in particular if you did anything to manually install the Python dependencies, or if you have done anything to your `sys.path` in the Blender Python?

**Comment by Moult** [comment]
@Sinasta actually on second thought, a Sverchok installed prior to [this commit 4 days ago](https://github.com/nortikin/sverchok/commit/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40) would've had the old Ladybug with it. It has now been purged. I believe the old Ladybug had their own `pip install` operator, which would trigger what you saw. If this was the case, no worries, you no longer need to rely on that pip install, so just purge it, update Sverchok core while you're at it, and it should recognise this addon's bundled ladybug libraries.
